### ISSUE TITLE
[Feature]: more configuration on lit time/max lit time

### ISSUE THREAD

**Issue by Fer0x453** [cech12/UnlitCampfire#42]
### Describe the Feature

1.20.1 forge. 

1) I noticed that you cannot add more fuel to _campfire_ if _lit time_ is >= than the number set in settings. So the problem is that for example I want to have a small **default**  _lit time_ when I place _campfire_ and then be able to add more fuel witch will increase _lit time_ over the **default number** so we can add a _**max lit time**_ here (0 - infinite), for example, witch you can set up in config.

2) And another thing is that I can't modify _lit time_ for different **items** and can't add **new items** from another mod, for example. I think it will also resolve a lot of issues with incompatibility.

3) Also there is a problem there I can't add sticks as fuel first of them will cook as torches. I think you can resolve it by adding ability to add fuel while squating(shifting).

---Unnecessary feature---
You can add ability to lit up campfire from torches (but it is basically an option from 2nd paragraph)

**Comment by cech12** [comment]
Thanks for your ideas!

1. I thought about such a config option. I will add it :)
2. you can add all items that can be used as burnable in a furnace. but q possibility to add other items is an interesting idea. I will think about that :)
3. which mod are you using for the torch recipe. maybe removing it could be an option ^^
4. also an interesting idea. but maybe that should be another mod ^^

**Comment by Fer0x453** [comment]
Thank you for quick responce! I didn't expect you to respond that fast.

1) glad to hear, I'll be waiting for that.
2) Yea, but for example I have an item witch mother mod didn't classified as burnable, then I can't use it. And for modifying lit time I think the easiest way is to put exeption option in config, so there won't be a ton of lines in config file.

**Comment by cech12** [comment]
Hey @Fer0x453,

I have added new config options "campfireMaxLitTimeExtension" and "soulCampfireMaxLitTimeExtension" where the lit time can be extended with burnables. (in the upcoming version 1.21-3.1.1.0)

For items, that are not defined as burnable: You can try using this mod: https://modrinth.com/mod/configured-burn-time or  contact the mod developer to add the items as burnables (would be the better way to be compatible with multiple other mods)

Your torch issue is related to the fact, that you have a mod, that adds a campfire recipe to create torches. The idea here is that items that can be crafted at the campfire are not lost as burnable, since right-clicking here by default places items to cook and does not burn them. In your case, this is a special case for which I do not want to write any extra code, as that would lead to more confusion than help. A workaround is, to add up to 4 items to block the "cooking" places and then add your sticks to extend the burn time. 

Thanks again for your ideas and I hope you enjoy the changes. :)

**Comment by Fer0x453** [comment]
Sorry, couldn't answer before, I'm busy for now, but thank you for your job. Sadly I would not be able to check mod changes for a while, but I will when I can 🤝
