### ISSUE TITLE
[Bug]: Crash on Startup With Poisonous Potato Update Mod

### ISSUE THREAD

**Issue by CraftyZombie** [cech12/UnlitCampfire#50]
### Minecraft Version

1.20.1

### Mod Loader

Forge

### Mod Loader Version

47.3.12

### Mod Version

1.9.1.1

### Modpack or other Mod

https://www.curseforge.com/minecraft/mc-mods/reimagining-potatoes
[Forge]PoisonousPotatoUpdate-1.20.1-1.0.0

### Describe the Issue

The game crashes on startup.

### Logs

https://gist.github.com/CraftyZombie/8fd66f06f28dd96fa1703fa14a91fc04

### Do you use any performance-enhancing mods (e.g. OptiFine)?

N/A

**Comment by cech12** [comment]
Thanks for your report! I will look into that when I have time :)

**Comment by cech12** [comment]
Thanks again for your report! The startup crash is fixed in the upcoming versions:
- 1.20.1-1.9.1.2
- 1.20.4-2.3.1.2
- 1.20.6-2.5.1.2
- 1.21-3.1.1.5
- 1.21.3-3.2.0.1

Unfortunately, the Poisonous Potato Update mod does not natively support the Unlit Campfire features for its FryingTableBlock although it is a CampfireBlock. That maybe could lead to some incompatibilities, which I did not tested. But if there are incompatibilities you should contact the mod developer of the Poisonous Potato Update mod to support that. :)
