### ISSUE TITLE
[Bug]: Ancient Aether's ambrosium campfire doesn't light

### ISSUE THREAD

**Issue by StockiesLad** [cech12/UnlitCampfire#53]
### Minecraft Version

1.20.1

### Mod Loader

Forge

### Mod Loader Version

47.3.12

### Mod Version

1.20.1-1.9.1.2

### Modpack or other Mod

Ancient Aether

### Describe the Issue

Ancient Aether's ambrosium campfire won't light **even in the overworld**; it just spawns a fireblock instead of lighting it up. I checked their code and they basically just copy the normal campfire properties and extend the right classes. So there shouldn't be a reason as to why it isn't working.

Moreover, could a tag be added like hardcore torches & carbonize? Where an item with x tag could ignite the mod's specified blocks. This way, ambrosium (or something similar) could be added to it to work in the aether.

### Logs

https://gist.github.com/StockiesLad/5f18b3b8d267ceb286d023fb25014dff

### Do you use any performance-enhancing mods (e.g. OptiFine)?

The issue is server-side...

**Comment by cech12** [comment]
Thanks for your report! I will look into that when I have time :)

Hint: There are also server-side performance enhancing mods ;)

**Comment by cech12** [comment]
@StockiesLad Yes, the campfire initially doesn't burn with the Unlit Campfire mod, but if you, for example, turn off the Ambrosium Campfire with a shovel (even without Unlit Campfire mod), you can't light it with Flint and Steel as well. So, this is an issue in the Ancient Aether mod and not due to incompatibility.

The point of this mod is that campfires don't burn from the start, and that is fulfilled here. :) A tag for items which can ignite campfires is out of scope of this mod. 

Please open an issue in Ancient Aether's repository.

**Comment by StockiesLad** [comment]
> @StockiesLad Yes, the campfire initially doesn't burn with the Unlit Campfire mod, but if you, for example, turn off the Ambrosium Campfire with a shovel (even without Unlit Campfire mod), you can't light it with Flint and Steel as well. So, this is an issue in the Ancient Aether mod and not due to incompatibility.
> 
> The point of this mod is that campfires don't burn from the start, and that is fulfilled here. :) A tag for items which can ignite campfires is out of scope of this mod.
> 
> Please open an issue in Ancient Aether's repository.

Ah I see. I'll do that
